### Obtener todas las movies
GET http://localhost:1234/movies


### Recuperar una movies por id
GET http://localhost:1234/movies/b32af11a-1624-4720-ab62-9c30dc06d750

### Obtener movies por genero mediante query string
GET http://localhost:1234/movies?genre=Action

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Action",
    "Drama"
  ]
}

### Actualizar una pelicula 
PATCH http://localhost:1234/movies/9603305e-6e3c-42f4-8742-edb5bb5558aa
Content-Type: application/json

{
  "year": 1993,
  "duration": 90,
  "title": "No no no no"
}